apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "dkron.name" . }}
  labels:
    app: {{ template "dkron.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: {{ .Values.images.dkron.name }}
          servicePort: 80
